name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Remove Gradle Java Home
        run: |
          echo "ORG_GRADLE_PROJECT_org_gradle_java_home and org.gradle.java.home will be unset"
          unset ORG_GRADLE_PROJECT_org_gradle_java_home
          unset ORG_GRADLE_PROJECT_org.gradle.java.home
          rm -f ~/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
