name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$JAVA_HOME"
        echo "JAVA_HOME_NO_TRAILING_SLASH=${JAVA_HOME%/}" >> $GITHUB_ENV
        export JAVA_HOME="${JAVA_HOME%/}"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
