name: Build Android APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Java version:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Make gradlew executable
      run: |
        echo "Setting execute permission for gradlew:"
        chmod +x ./gradlew
        echo "Verifying permissions:"
        ls -la gradlew
        echo "Testing gradlew:"
        ./gradlew --version
        
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30 